### ISSUE TITLE
Multiple boards issue

### ISSUE THREAD

**Issue by chelo-kjml** [Clariity/react-chessboard#47]
Hi guys, I am trying to implement this board in a project using react 18 and latest version of material ui framework for styles. I've implemented 3 different boards (all using different id attribute), one for big screen, other for medium and one for small screens and depending on resolution i use display -> none to hide it or not. 

Problem is that after implementing three boards at the same time I am getting this error when trying to make a move:

> Uncaught Error: Cannot have two HTML5 backends at the same time.
    at HTML5BackendImpl.setup (index.esm.js:3650:1)
    at DragDropManagerImpl.handleRefCountChange (index.esm.js:890:1)
    at Object.dispatch (index.esm.js:308:1)
    at HandlerRegistryImpl.addSource (index.esm.js:1595:1)
    at registerSource (index.esm.js:2448:1)
    at registerDragSource (index.esm.js:2985:1)
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:1)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:1)
    at commitLayoutEffects_begin (react-dom.development.js:24674:1)

Having multiple boards is a limitation of this project or am I doing something wrong? Could you please clarify a little bit? Thanks in advance!

**Comment by Clariity** [comment]
Hello, thank you for raising this, I'm busy currently but I will look into it this weekend, this may be a result of changes in #39

**Comment by Clariity** [comment]
Should be fixed in https://github.com/Clariity/react-chessboard/releases/tag/v1.3.1 

Please upgrade and confirm

**Comment by chelo-kjml** [comment]
Sorry for the late response, I've being working on other things. I've just tried it and everything looks good now. Thanks for the quick fix!
